//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SbcapcdOrg.PdePermit.Device.Controls {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class usrDevice {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal usrDevice() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SbcapcdOrg.PdePermit.Device.Controls.usrDevice", typeof(usrDevice).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap bindingNavigatorMoveFirstItem_Image {
            get {
                object obj = ResourceManager.GetObject("bindingNavigatorMoveFirstItem.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bindingNavigatorMoveLastItem_Image {
            get {
                object obj = ResourceManager.GetObject("bindingNavigatorMoveLastItem.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bindingNavigatorMoveNextItem_Image {
            get {
                object obj = ResourceManager.GetObject("bindingNavigatorMoveNextItem.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bindingNavigatorMovePreviousItem_Image {
            get {
                object obj = ResourceManager.GetObject("bindingNavigatorMovePreviousItem.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Point bnDeviceList_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("bnDeviceList.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        internal static System.Drawing.Point bsDeviceList_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("bsDeviceList.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        internal static System.Drawing.Point bsNavigate_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("bsNavigate.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        internal static System.Drawing.Point bsPermitsWithDevice_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("bsPermitsWithDevice.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        internal static System.Drawing.Point bsSourceFaciltiyPermit_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("bsSourceFaciltiyPermit.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        internal static System.Drawing.Point bwDevice_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("bwDevice.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        internal static System.Drawing.Point bwFillNavigation_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("bwFillNavigation.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        internal static System.Drawing.Point bwLoadDevice_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("bwLoadDevice.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        internal static System.Drawing.Point dsDevice_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("dsDevice.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        internal static System.Windows.Forms.ImageListStreamer imlDeviceTree_ImageStream {
            get {
                object obj = ResourceManager.GetObject("imlDeviceTree.ImageStream", resourceCulture);
                return ((System.Windows.Forms.ImageListStreamer)(obj));
            }
        }
        
        internal static System.Drawing.Point imlDeviceTree_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("imlDeviceTree.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        internal static System.Drawing.Point timer1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("timer1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        internal static System.Drawing.Point tipDevice_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("tipDevice.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tsbtnColapseTree_Image {
            get {
                object obj = ResourceManager.GetObject("tsbtnColapseTree.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tsbtnExpandTree_Image {
            get {
                object obj = ResourceManager.GetObject("tsbtnExpandTree.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tsbtnGetPermits_Image {
            get {
                object obj = ResourceManager.GetObject("tsbtnGetPermits.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tsbtnGoToDevice_Image {
            get {
                object obj = ResourceManager.GetObject("tsbtnGoToDevice.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tsbtnStopTimer_Image {
            get {
                object obj = ResourceManager.GetObject("tsbtnStopTimer.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
